<?php

/**
 * @var \Thanhtrung1999\HelloWorld\Block\Display $block
 */

echo $block->sayHello();
?>

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color:#f2f2f2; }
    .post-id{width:2%} .post-name{width:30%}
</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php if (!empty($block->getPostCollection())):?>
    <?php foreach ($block->getPostCollection() as $key => $item):?>
        <tr>
            <td><?= $item->getPostId();?></td>
            <td><?= $item->getName();?></td>
            <td><?= $item->getPostContent();?></td>
        </tr>
    <?php endforeach;?>
    <?php endif;?>
</table>

</body>
</html>
