<?php
/**
 * @var \Thanhtrung1999\Hospital\Block\Index $block
 */
echo "Value: " . $block->enableShowListHospitals();
?>

<?php if ($block->enableShowListHospitals()):?>
    <div class="hospitals-contents">
        <table>
            <tr>
                <th class="hospital-id">Id</th>
                <th class="hospital-name">Name</th>
                <th>Address</th>
                <th class="phone-number">Phone number</th>
            </tr>
            <?php if (!empty($block->getHospitalsCollection())):?>
                <?php foreach ($block->getHospitalsCollection() as $key => $item):?>
                    <tr>
                        <td><?= $item->getId();?></td>
                        <td><?= $item->getName();?></td>
                        <td><?= $item->getAddress();?></td>
                        <td><?= $item->getTelephone();?></td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        </table>
    </div>
<?php else:?>
    <h2>Disable</h2>
<?php endif;?>
